
#INSTALLATION OF THE OPERATING SYSTEM
FROM openjdk:17-jdk

LABEL authors="indiagator"

#PLACEMENT OF THE EXECUTABLE [MICROSERVICE] ON THE IMAGE
COPY target/configserverboot3-0.0.1-SNAPSHOT.jar app.jar

#EXPOSE PORTS FOR INCOMING TRAFFIC - HOST_PORT:CONTAINER_PORT
EXPOSE 8888:8888

#INSTALLING UTILITIES
#RUN apt-get update
#RUN apt-get install -y gcc
#RUN apt-get install -y curl

#ENTRYPOINT OF THE CONTAINER THROUGH THE MICROSERVICE
ENTRYPOINT ["java","-jar","app.jar"]