
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/subhra-EE-2011/microservices-config.git
          refresh-rate: 1
          searchPaths: '{application}'
          clone-on-start: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}


logging:
  level:
    org:
      springframework: DEBUG

zipkin:
  baseUrl: http://localhost:9411

management:
  endpoints:
    web:
      exposure:
        include: refresh






